### ISSUE TITLE
Please check the new init.sh with Fuse 6.2 in branch fuse62

### ISSUE THREAD

**Issue by weimeilin79** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#5] opened 2015-07-10 08:08 UTC
Updated the init.sh with new Fuse 6.2, please verify it. Thanks!

**Comment by eschabell** [comment] 2015-07-10 11:20
Have added readme updates to the branch but testing init now gives that same issue seen before during fuse installation (I am using java 7):

383 [sshd-SshClient[11c2e5bb]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 7a:73:ad:f0:cb:19:13:4e:8e:7f:ad:fd:ef:29:09:de] presented unverified {} key: {}

This keeps repeating....

**Comment by weimeilin79** [comment] 2015-07-10 23:07
Tested, 
I change the checking interval to 10 seconds, so it does not look like it keeps repeating. But it take 7-8 minutes in my laptop for all 6 containers to provision properly.

**Comment by eschabell** [comment] 2015-07-11 18:19
Ok, so let it run longer but at 4 mins it now gives build errors before that waiting starts... logs:

[INFO] ------------------------------------------------------------------------
[INFO] Building Travel Agency Flight Contract first Web Endpoint Service (CXF) 1.0
[INFO] ------------------------------------------------------------------------
[WARNING] Error injecting: org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactory
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.eclipse.aether.connector.wagon.WagonProvider was bound.
  while locating org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactory

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:36)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.wire.EntrySetAdapter$ValueIterator.next(EntrySetAdapter.java:102)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:103)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:603)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] Error injecting: org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactory
Exception in thread "DefaultMetadataResolver-0-1" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.eclipse.aether.connector.wagon.WagonProvider was bound.
  while locating org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactory

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:36)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.eclipse.aether.connector.wagon.WagonProvider was bound.
  while locating org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactory
  at ClassRealm[plugin>io.fabric8:fabric8-maven-plugin:1.2.0.redhat-133, parent: sun.misc.Launcher$AppClassLoader@2bb0bf9a] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  at ClassRealm[plugin>io.fabric8:fabric8-maven-plugin:1.2.0.redhat-133, parent: sun.misc.Launcher$AppClassLoader@2bb0bf9a] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.wire.EntrySetAdapter$ValueIterator.next(EntrySetAdapter.java:102)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:103)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:603)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
PlexusBindingModule)
  while locating org.eclipse.aether.spi.connector.RepositoryConnectorFactory annotated with @com.google.inject.name.Named(value=wagon)

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.wire.EntrySetAdapter$ValueIterator.next(EntrySetAdapter.java:102)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:103)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:603)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] Error injecting: org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactoryException in thread "DefaultMetadataResolver-0-0" 
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.eclipse.aether.connector.wagon.WagonProvider was bound.
  while locating org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactory

1 error
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.eclipse.aether.connector.wagon.WagonProvider was bound.
  while locating org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactory
  at ClassRealm[plugin>io.fabric8:fabric8-maven-plugin:1.2.0.redhat-133, parent: sun.misc.Launcher$AppClassLoader@2bb0bf9a] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  at ClassRealm[plugin>io.fabric8:fabric8-maven-plugin:1.2.0.redhat-133, parent: sun.misc.Launcher$AppClassLoader@2bb0bf9a] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.eclipse.aether.spi.connector.RepositoryConnectorFactory annotated with @com.google.inject.name.Named(value=wagon)

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.wire.EntrySetAdapter$ValueIterator.next(EntrySetAdapter.java:102)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:103)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:603)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:36)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.wire.EntrySetAdapter$ValueIterator.next(EntrySetAdapter.java:102)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:103)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:603)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "DefaultMetadataResolver-0-2" [INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.eclipse.aether.connector.wagon.WagonProvider was bound.
  while locating org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactory
  at ClassRealm[plugin>io.fabric8:fabric8-maven-plugin:1.2.0.redhat-133, parent: sun.misc.Launcher$AppClassLoader@2bb0bf9a] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  at ClassRealm[plugin>io.fabric8:fabric8-maven-plugin:1.2.0.redhat-133, parent: sun.misc.Launcher$AppClassLoader@2bb0bf9a] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
  while locating org.eclipse.aether.spi.connector.RepositoryConnectorFactory annotated with @com.google.inject.name.Named(value=wagon)

1 error[INFO] Travel Agency Fuse Demo Parent ..................... SUCCESS [  7.034 s]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.wire.EntrySetAdapter$ValueIterator.next(EntrySetAdapter.java:102)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:103)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:603)

	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[INFO] Travel Agency Flight Contract first Web Endpoint Service (CXF) FAILURE [  0.027 s]	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[INFO] Travel Agency Hotel Contract first Web Endpoint Service (CXF) SKIPPED

	at java.lang.Thread.run(Thread.java:745)
[INFO] Travel Agency Promotion Flights service (JDBC) ..... SKIPPED
[INFO] Travel Agency Promotion Hotel service (JDBC) ....... SKIPPED
[INFO] Travel Agency Flights Booking service (JPA) ........ SKIPPED
[INFO] Travel Agency Hotel Booking service (JPA) .......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.011 s
[INFO] Finished at: 2015-07-11T13:16:36-04:00
[INFO] Final Memory: 36M/234M
[INFO] ------------------------------------------------------------------------
[ERROR] Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) No implementation for org.eclipse.aether.connector.wagon.WagonProvider was bound.
[ERROR] while locating org.eclipse.aether.connector.wagon.WagonRepositoryConnectorFactory
[ERROR] at ClassRealm[plugin>io.fabric8:fabric8-maven-plugin:1.2.0.redhat-133, parent: sun.misc.Launcher$AppClassLoader@2bb0bf9a] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] at ClassRealm[plugin>io.fabric8:fabric8-maven-plugin:1.2.0.redhat-133, parent: sun.misc.Launcher$AppClassLoader@2bb0bf9a] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.eclipse.aether.spi.connector.RepositoryConnectorFactory annotated with @com.google.inject.name.Named(value=wagon)
[ERROR] 
[ERROR] 1 error
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
Testing profiles,retry when not ready
371 [sshd-SshClient[11c2e5bb]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, a2:d1:f7:f1:b9:6a:09:bb:db:c6:87:d2:bf:84:8e:73] presented unverified {} key: {}

**Comment by eschabell** [comment] 2015-07-11 18:44
After this long I gave up...

373 [sshd-SshClient[417f6125]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, a1:ad:ba:51:33:63:5b:3f:4f:1c:df:3d:a1:eb:0b:c0] presented unverified {} key: {}
^C

real	23m51.161s
user	9m5.893s
sys	0m52.683s

**Comment by weimeilin79** [comment] 2015-07-11 22:07
1. The problem is because you need maven 3.1.1 - 3.2.4 and it will not support any thing above until Fuse 6.2.1
2. It's taking forever because of first error...

**Comment by eschabell** [comment] 2015-07-11 23:54
We release a new product and it needs users to downgrade maven?????

-- erics (from phone)

**Comment by weimeilin79** [comment] 2015-07-12 00:04
there are workaround to do this... sigh... but not sure if I want to redo the entire deployment steps and then trash it after 6.2.1....

**Comment by weimeilin79** [comment] 2015-07-14 13:07
I rewrite the entire deployment step and it's a workaround. So no special maven needed.

**Comment by eschabell** [comment] 2015-07-14 16:31
Still not working for me with 3.3.3 or 3.1.1, both give a cycle on this message type until I end it (note the time it ran):

411 [sshd-SshClient[11c2e5bb]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 3f:0c:3b:f0:e4:42:fa:86:57:9f:e3:cf:ac:8f:c7:87] presented unverified {} key: {}
376 [sshd-SshClient[66a7086f]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 3f:0c:3b:f0:e4:42:fa:86:57:9f:e3:cf:ac:8f:c7:87] presented unverified {} key: {}
450 [sshd-SshClient[12786119]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 3f:0c:3b:f0:e4:42:fa:86:57:9f:e3:cf:ac:8f:c7:87] presented unverified {} key: {}
405 [sshd-SshClient[1d2eb9c8]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 3f:0c:3b:f0:e4:42:fa:86:57:9f:e3:cf:ac:8f:c7:87] presented unverified {} key: {}
^C

real	54m18.924s
user	19m33.257s
sys	1m47.130s

**Comment by weimeilin79** [comment] 2015-07-15 03:46
Please checkout the fuse62 again. 
Changes made this time:
1. Add max number of retries at the end so it does not run forever.
2. Force process to stop even when still provisioning.

**Comment by eschabell** [comment] 2015-07-15 21:19
Pushed some changes for maven project, now clear what version does not work and the looping still happening so not stopping....

**Comment by weimeilin79** [comment] 2015-07-21 06:00
I ask 2 red hatters to check, looks like their machine is running ok.

**Comment by eschabell** [comment] 2015-08-05 19:05
Build now works here too... takes a very long time, but works, here are my findings:

1. Time to install (not including login and starting containers): 8m 10s, longer than previous Fuse version... might want to raise issues soon as performance keep degrading. 

2. Adjusted init.sh documentation at the end to refer to Containers instead of Runtime tab and adjusted Readme documentation too for 2 above. Also added new version once merged this branch can be tagged.

3. Before we merge need to have Andrew Block update the init.bat, raised an issue for this so he can do it in the fuse62 branch: 

jbossdemocentral/bpms-fuse-travel-agency-integration-demo#6

Only issue blocking now is 3 above...

**Comment by eschabell** [comment] 2015-08-12 22:02
Did some further start up to screen grab for the release, starting the containers gives me failures to start...
![screen shot 2015-08-12 at 5 59 07 pm](https://cloud.githubusercontent.com/assets/437001/9237909/3382ffba-411c-11e5-9855-7db7e300ac1d.png)

The screenshot of one containers failure...

![screen shot 2015-08-12 at 5 53 53 pm](https://cloud.githubusercontent.com/assets/437001/9237910/3ba6328e-411c-11e5-8fb9-8285e767a145.png)

**Comment by eschabell** [comment] 2015-08-21 18:08
No changes after trying this with a steady IP (you suggested losing IP would break it), new clean install of the branch, same results... this is broken right now.

**Comment by weimeilin79** [comment] 2015-08-23 04:26
Your error looks like zookeeper is picking your network as hostname http://jbossbpm.local and this host name cannot be resolved by your machine that cause the problem. Again, network setting. I have change the zookeeper to manually setup the IP address to 127.0.0.1. That will fix the artifact not found problem.

**Comment by weimeilin79** [comment] 2015-08-23 11:28
Please don't test yet, I change the transaction manager, still needs to update!

**Comment by weimeilin79** [comment] 2015-08-24 00:47
OK, Now everything in Fuse 62 fixed and updated transaction manager built-in in Aries. And Updated the fuse image under docs/

**Comment by eschabell** [comment] 2015-08-26 01:37
None of the containers with micro services start, giving these errors:



Provision Exception:

        io.fabric8.common.util.MultiException: Error

          at io.fabric8.agent.download.impl.MavenDownloadManager$MavenDownloader.(MavenDownloadManager.java:93)

          at io.fabric8.agent.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:71)

          at io.fabric8.agent.utils.AgentUtils.downloadRepositories(AgentUtils.java:198)

          at io.fabric8.agent.service.Agent.provision(Agent.java:182)

          at io.fabric8.agent.DeploymentAgent.doUpdate(DeploymentAgent.java:642)

          at io.fabric8.agent.DeploymentAgent$2.run(DeploymentAgent.java:256)

          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)

          at java.util.concurrent.FutureTask.run(FutureTask.java:262)

          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

          at java.lang.Thread.run(Thread.java:745)

        java.io.IOException: Error downloading mvn:org.blogdemo.travelagency/features/1.0/xml/features

          at io.fabric8.agent.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:49)

          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)

          at java.util.concurrent.FutureTask.run(FutureTask.java:262)

          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)

          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)

          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

          at java.lang.Thread.run(Thread.java:745)

        Caused by: java.io.IOException: Error resolving artifact org.blogdemo.travelagency:features:xml:features:1.0: Could not find artifact org.blogdemo.travelagency:features:xml:features:1.0 in repo_-1231785675 (http://127.0.0.1:8181/maven/download/)

          at io.fabric8.maven.url.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:512)

          at io.fabric8.maven.url.internal.AetherBasedResolver.resolveFile(AetherBasedResolver.java:453)

          at io.fabric8.maven.url.internal.AetherBasedResolver.resolveFile(AetherBasedResolver.java:438)

          at io.fabric8.maven.url.internal.AetherBasedResolver.download(AetherBasedResolver.java:414)

          at io.fabric8.agent.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:33)

          at io.fabric8.agent.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:40)

        ... 7 more

**Comment by eschabell** [comment] 2015-08-26 01:38
Note, using (still required to downgrade maven?) maven 3.2.3.

**Comment by weimeilin79** [comment] 2015-08-26 20:06
Tried to duplicate the error, but can't. Can you see what is your outcome when you deploy?[INFO] 
[INFO] --- maven-bundle-plugin:2.3.7:install (default-install) @ features ---
[INFO] Installing org/blogdemo/travelagency/features/1.0/features-1.0.jar
[INFO] Writing OBR metadata
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Travel Agency Fuse Demo Parent .................... SUCCESS [0.352s]
[INFO] Travel Agency Flight Contract first Web Endpoint Service (CXF)  SUCCESS [8.902s]
[INFO] Travel Agency Hotel Contract first Web Endpoint Service (CXF)  SUCCESS [2.229s]
[INFO] Travel Agency Promotion Flights service (JDBC) .... SUCCESS [1.006s]
[INFO] Travel Agency Promotion Hotel service (JDBC) ...... SUCCESS [0.872s]
[INFO] Travel Agency Flights Booking service (JPA) ....... SUCCESS [1.110s]
[INFO] Travel Agency Hotel Booking service (JPA) ......... SUCCESS [0.540s]
[INFO] Travel Agency Features ............................ SUCCESS [0.596s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.411s
[INFO] Finished at: Wed Aug 26 15:58:00 EDT 2015
[INFO] Final Memory: 44M/500M
[INFO] ------------------------------------------------------------------------
  - Create Flight Web Endpoint Porfile
  - Create Hotel Web Endpoint Porfile
  - Create Flight Booking Service Porfile
  - Create Hotel Booking Service Porfile
  - Create Flight Promotion Service Porfile
  - Create Flight Hotel Service Porfile
Testing profiles,retry when not ready
683 [sshd-SshClient[6cf5c440]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 37:97:16:f0:3f:64:cc:c1:1a:d4:a7:28:72:5a:4a:75] presented unverified {} key: {}

**Comment by eschabell** [comment] 2015-08-28 11:29
Problem as we debugged was somewhere in fuse not handling ${user.hom}/path-to-maven-repo when set in setttings.xml file.... need to raise a bug.

**Closed by eschabell** 2015-08-28 11:29 UTC
